* 💪 Идеальный программист: как стать провессионалом разработки ПО / Мартин Роберт

** Глава 1. Кто такой профессионал?
  - Ответственный человек, добросовестно выполняющий свою работу и целенаправлено совершенствующийся.
  - Профессионал НЕ релизит код без тестирования, а говорит, что он не успевает, говорит заранее, чтобы его менеджер смог что-то сделать. Это ответственное поведение.
  - Профессионал НЕ вредит функционалу поэтому использует автотесты, чтобы быстро проверять работает ли его программа или нет.
  - Профессионал НЕ вредит структуре программы поэтому пишет код так, чтобы его можно было быстро изменять в будущем.
  - Профессионал разбирается в предметной области: для этого он читает минимум одну книгу в той предметной области с которой работает.
  - Профессионал уверен в своих силах, чтобы либо взяться за сложную задачу либо найти силы сказать нет, но в то же время понимает, что может ошибиться.
  - Профессионал думает об интересах заказчика.
  - Как избежать выгорания? Работай 40 часов в неделю на работодателя и еще 10-20 часов посвяти себе: читай книги, пробуй новые языки, экспериментируй, в общем выбирай интересные вещи - это важно.

** Глава 2. Почему нужно говорить нет и почему здоровые конфликты создают лучший продукт?
  - Если нельзя уложиться в дедлайн или в принципе сделать задачу, то так об этом и скажи, как бы тебе ни было страшно.
  - В процессе обсуждения можно изменить требования или сдвинуть дату релиза.
  - В процессе конфронтации каждый член команды преследует свою цель и совместно они находят общую цель. Цель – создать востребованный продукт, а это значит, что нужно разобраться со множеством конфликтующих интересов.

** Глава 3. Почему нельзя ничего обещать впустую?
  - Слова "попробую", "надо бы" - верный признак того, что ничего сделано не будет.
  - Другие люди полагаются на твои слова и ты их можешь подвести. Лучше, чтобы они сразу знали, что что-то сделано не будет: тогда у них останется время для маневра, а ты не будешь тратить их время зря.
  - Обещай сделать только выполнимые вещи и в четко оговоренный срок.
  - Если дал обещание и понимаешь, что не можешь его сдержать - сразу сообщи об этом и помоги другим людям подготовиться к решению этой проблемы.
  -
