* 🏗️ Проектирование процесса проектирования / Брукс Фредерик

** 1. Что такое рациональная модель проектирования?
  - 1. Определи цель.
  - 2. Определи требования.
  - 3. Определи функцию пригодности: каждый компонент имеет насыщение, так что это не просто сумма всех частей. При достижении нужного уровня нет смысла дальше улучшать этот компонент.
  - 4. Определи основные ограничения: особенно те, которые растут экспоненциально. Их нужно держать под контролем.
  - 5. Перебери варианты в пространстве проектирования с учетом ограничений.

** 2. Что не так с рациональной моделью проектирования?
  - Требования на старте проекта обычно неясны. Быстрые итерации помогают клиентам сформулировать, что они действительно хотят. Не стоит сразу ожидать от них ясности поскольку они не понимают как вещи сложнее реализовать, а какие легче.
  - При поиске в дереве решений (пространстве проектирования) возникает комбинаторный взрыв.
  - Когда наступит следующий ноябрь? Вопрос на выяснение какая модель в голове у собеседуемого. В идеале пространственная.

** 3. Какие проблемы могут быть с требованиями?
  - Если комитет вырабатывает требования, то без обратной связи (людей с опытом эксплуатации подобных систем) требования могут стать либо нереализуемыии в принципе либо приаедут к ухудшению других характеристик. Пример с вертолетом, который должен суметь пересечь Атлантику.
