* ➡️ Цель: дело не в везении / Голдратт Элияху

** Четыре проблемы менеджмента:
1. Осознать, что есть проблема, а не просто "здесь что-то не так".
2. Что нужно менять?
3. На что нужно менять?
4. Как провести изменения?

** 1. Как осознать, что есть проблема?
  - 1. Выписать все нежелательные явления: если случится Х, то будет У.
  - 2. Обсудить нежелательные явления, не предлагая решения.
  - Пример с яхтой на двоих с братом жены.

** 2. Как искать корневую причину нежелательных явлений? Как понять что именно менять?
  - Выстрой причинно-следственные связи и опиши нежелательные явления.
  - Затем покажи оппоненту и пусть он с ними согласится или предложит свое видение логических связей. Это ключевой момент: нужно описать логическую цепочку, существующую и важную для оппонента.
  - Еще раз: все нежелательные явления нужно связать причинно-следственными связями (НЖЯ1 ведет к НЖЯ2). Как правило в основе текущего положения дел всегда лежит одна и та же ключевая проблема. Вот с ней и надо разбираться.
  - Этот инструмент называется «дерево текущей реальности».

** 3. Как разрешить конфликт?
  - Признать, что надо искать компромисс.
  - Я подумаю - это обещание. Надо назначить время и подумать.
  - Итерация 1:
    - Чего хочу я? Дочь дома до 10 вечера.
    - Чего хочет дочь? Дома до 12 вечера.
  - Итерация 2:
    - Чего на самом деле хочу я? Дочь в безопасности.
    - Чего на самом деле хочет она? Хочет быть популярной среди друзей.
  - Какая цель тут общая? Зачем вообще вести переговоры?
    - Чувствовать себя комфортно в семье. Эта цель общая для всех членов семьи.
    - Можно ли обеспечить безопасность дочери, но вернуться в 12? Да, можно забрать ее самому.
  - Этот инструмент называется «грозовая туча».

** 4. Как составить план решения проблемы?
  - Сначала определи амбициозную цель.
  - Потом определи препятствия на пути к цели. Прямо пиши списком без оценки.
  - Теперь все просто: план возникнет из задач по ликвидации препятствий.
  - Нюанс: можно вовлечься эмоционально и решить, что препятствие непреодолимо. Старайся думать чисто логически без привлечения эмоций.
  - Еще раз: именно цель как бы тянет за собой список препятствий (его надо только записать для анализа), а они уже тянут список действий.
  - Препятствия могут зависеть друг от друга и это определить очередность промнжуточных задач в плане.
  - Этот инструмент называется «дерево предпосылок».
