👥 Человеческий фактор: успешные проекты и команды / ДеМарко Том, Листер Тимоти

** I. Отличается ли работа с людьми от разработки программ?
*** Глава 1. Что приводит к провалу проекта?
- У крупных проектов доля провалов выше, чем у средних. Провал - это закрытие или невостребованность проекта.
- Технологические сложности редко приводят к провалу проектов. Наоборот, проблемы с людьми приводят к провалу проектов.
- Если руководитель много времени уделяет технологиям и мало людям, то проект провалится.
- Ловушка: если руководитель был хорошим реализатором, то ему будет сложно сместить фокус внимания с деталей реализации и подняться на уровень выше.
- Ловушка: подавляющее большинство проектов относительно просты технически и сложность находится на уровене выше: бизнес (как регулярно зарабатывать деньги) и люди (которые делают бизнес и которые имеют разные интересы).
- Метафора: искать ключи не в том месте где потерял их, а там где светло, потому что так удобнее.

*** Глава 2. Отличается ли производство булок от разработки программ?
- Эксперименты: нужны в разработке, могут быть вредны на производстве однотипной продукции. Следовательно, ошибки - это часть процесса разработки. Все, что нужно сделать, это не повторять их по несколько раз. Если человек не делает ошибок, то скорее всего он не экспериментирует, не пробует новое, а значит не учится.
- Внешняя мотивация (пинки): не нужна в разработке (мы же делаем относительно нетиповые вещи) и даже вредна, но может быть нужна на производстве (где линейная зависимость между интенсивностью работы и хорошо измеримым результатом, а сотрудники работают вынужденно). В идеале пинки вредны: лучше вообще не брать на работу людей без желания ее делать. Задача менеджера - найти людей с внутренней мотивацией и либо способных выполнять работу либо способных быстро научиться.
- Взаимозаменяемость людей: в разработке меньше, чем на производстве. Удовлетворение индивидуальных особенностей (мне нужно работать из дома) помогает повысить производительность человека. Если их не учитывать, то будет снижение производительности.
- Оценивай людей по их качественному вкладу в проект, а не по количеству строк кода или количеству закрытых задач. Пример ДеМарко с женщиной-катализатором на успешных проектах.
- Средний разработчик не читает книг и тратит до 5% времени на обдумывание задачи и сразу бросается ее делать.

*** Глава 3. Что не так со сверхурочной работой?
- У человека только одна жизнь, за которую можно сделать ограниченное количество вещей. Выбирая сверхурочную работу человек отказывается от чего-то другого, о чем он может пожалеть.
- Выгоревший (долгое время проработавший на пределе возможностей) обычно увольняется.
- Если учитывать возрастающую текучку, то систематические переработки сразу становятся невыгодны.
- Под давлением люди работают быстрее, но не лучше: страдает качество.

*** Глава 4. Кому нужен качественный продукт и насколько качественный он должен быть, чтобы оставаться рентабельным?
- Меньшее количество пользователей готово заплатить за более качественный продукт. Краткосрочно низкое качество оправдано.
- Обычно у разработчика более высокий стандарт качества, чем рынок готов заплатить.
- Долгосрочно низкое качество приведёт к банкротству: конкуренты сделают более качественный и более дешевый продукт.
- В какой-то момент нужно инвестировать в качество и позже оно приведёт к увеличению производительности.

*** Глава 5. Внутренняя или внешняя мотивация?
- Человеку с внутренней мотивацией нет смысла растягивать работу.
- Обьем рутинной работы действительно только растёт. Нужно прилагать усилия для ее уменьшения.

*** Глава 6. Есть ли волшебный способ, который сразу решит все проблемы проекта?
- Нет такого способа.
- Задача руководителя убирать препятствия с пути команды. Это и есть менеджмент.
- Люди - не модули. У каждого человека есть особенности, которые руководитель должен учитывать.


** II. Отвлечения: как сохранять фокус и при это общаться с другими?
*** Глава 10. Насколько падает производительность, когда нас отвлекают?
- Порядка 70% рабочего времени уходит на коммуникацию и отдых и только 30% на сосредоточенную работу одному.
- Для того, чтобы войти в поток, нужно 15 минут. Умножь это количество на число прерываний.
- Фактор среды = время непрерывной работы / время присутствия

*** Глава 11.  Сколько стоит отвлечение на телефонные звонки?
- Дорого: нужно прерваться немедленно и затем уйдёт примерно 15 минут, чтобы войти в поток после каждого звонка.
- Электронную почту можно проверять батчем, нужно лишь отключить оповещения.
- Со Слаком то же самое.
- Предпочитай асинхронную коммуникацию.
- Защищай сфокусированное время работы.

*** Глава 12. Зачем нужна дверь?
- Чтобы не отвлекаться и дать понять другим, что ты занят.
- Роскошь не нужна: если место просто удобное и нет отвлечений (гигиенические факторы), то интересная работа будет фактором мотивации.


** III. Кого нанимать?
*** Глава 14. Нужно ли единообразие профессионалам?
- Зачем программисту ходить в костюме? Понятно, что в отделе продаж обычно нужен деловой стиль. Почаще нужно спрашивать зачем делать это?
- Зачем нужно единообразие сотрудников? Там, где нужно четко следовать инструкциям, это помогает контролировать несоответствия.

*** Глава 15. Как проверять людей при найме?
- Прежде чем нанять жонглера нужно посмотреть насколько хорошо он жонглирует. Не сделать этого - это типичная ошибка.
- Попроси у кандидата портфолио (примеры его кода).
- Попроси кандидата рассказать об одном из проектов, над которым он работал. Пригласи команду на собеседование и после собеседования спроси их мнение о кандидате. Так больше шансов, что команда примет его.

*** Глава 16. Сколько стоит текучка кадров?
- 1-2 зарплаты на поиск и найм.
- 1-6 зарплат на выход на полную производительность.
- При увольнении сотрудника и найме нового повторить расчёт.
- Как правило эти затраты не учитываются руководителями.
- Если сотрудник работает в фирме менее двух лет, то стоимость скрытых затрат на текучку может составить до 30-50%.
- В краткосрочной перспективе эти затраты не будут видны. Немногие фирмы работают на долгосрочную перспективу.
- Лучшие компании вкладываются в своих сотрудников, например, в обучение и переобучение.

*** Глава 17. Какие системы самоизлечиваются?
- В автоматизированной системе поведение определено разработчиком. Такая система дёшево обрабатывает стандартные ситуации.
- Люди же способны быстро и дешево обрабатывать нестандартные ситуации.
- Для самоизлечения системы нужны люди, которые обработают нестандартную ситуацию.
- Методология помогает начать, но как только люди научились хоть немного делать свою работу, она можете быть нужна только тем, кто совсем не умеет думать.
- Не принимать стандарт, а скорее описать подход, который применялся в успешном проекте.
- Эффект Готорна: увеличили освещенность и производительность выросла, затем уменьшили освещенность и производительность выросла еще раз. К увеличению производительности приводил сам факт наличия изменений.
- Дай людям принимать решения, не связывай их по рукам и ногам.
- Нанимай людей умеющих думать и делать. Начни со стандарта, а затем убери его и дай людям принимать решения.


** IV. Как вырастить команду?
*** Глава 18. Как кристаллизируется команда?
- Не всякая группа людей является командой. Даже если они работают вместе.
- Если команда прошла кристаллизацию, то производительность команды выше суммы уровней производительности членов команды. При этом люди более довольны своей работой.
- Кристаллизация команды происходит тогда, когда участники начинают разделять общую цель и стремиться к ней. Даже если цель выбрана произвольно, члены команды принимают ее. Тут важно не добавить другую цель, которую команда не примет.
- Низкая текучка - показатель кристаллизации команды.
- Удовольствие от работы и ощущение элитарности работы в команде - это тоже показатель кристаллизации команды. Сам факт работы в такой команде является одной из самых сильных потребностей.

*** Глава 19. Чёрная команда как пример
- Группа инженеров по тестированию, которые находили удовольствие в поиске и нахождении багов. Фирмы выиграла от того, что клиенты не получали сырой продукт, а члены команды получали удовольствие от работы.
- Переход от «я крутой» к «мы крутые».

*** Глава 20. Как кристаллизировать команду?
- Гарантий нет, но есть факторы скорее полезные.
- Команда делает продукт, нужный людям. Чем лучше она его делает, тем лучше пользователям. Положительная связь.
- Члены команды и руководство доверяют друг другу. Люди должны совершать ошибки, чтобы научиться новому.
- Если человек делает рутинную задачу, то он должен понимать зачем.
- Члены команды общаются формально и неформально.
- Члены команды работают над одним проектом одновременно.
- Реальный срок завершения проекта.

*** Глава 21. Как приготовление ужина со спагетти влияет на командный успех?
- Члены команды познакомились во время ужина, который они сами приготовили. Это был их первый успех. Руководитель участвовал как член команды, команда самоорганизовалась.

*** Глава 22. Доверять или следить за каждым шагом?
- Люди периодически ошибаются, это нормально. Но если ты сосем не можешь доверить работу человеку и смириться с результатом, то такого человека брать в команду нельзя. История про адвоката и подпись не глядя.
- Проверяй результат, а не людей.
- Доверие в команде необходимо для ее кристаллизации.
- Некоторые очень продвинутые инженеры-одиночки могут компенсировать отсутствие кристаллизации, но все же лучше, чтобы команда стала целым.
- Как руководитель опирайся на естественный авторитет.

*** Глава 23. Что делает руководитель в сформировавшейся крутой команде?
- Доводит стратегию до сотрудников без погружения в детали реализации (но может помочь обсудить, сам не делает);
- Транслирует качество как ценность;
- Создаёт точки завершения для присвоения результатов. Здесь же возникает ощущение небольшого успеха;
- Создаёт ощущение элитарности команды (пример компании Xerox и билетов первого класса);
- Остаётся немного вдали: лидерство должно переходить от одного члена команды к другому, а команда оставаться группой равных;
- Поддерживает разнообразие: в разнородной команде проще быть самим собой.
- Если руководитель делает свою работу хорошо, а команда кристаллизовалась,  то кажется, что все вышеперечисленное происходит само собой.
- Смотри также доклад Мотивация 3.0 Пименова, там описывается этот процесс на уровне одного члена команды.


** V. Как получать удовольствие от работы?
*** Глава 24. Как привнести новое в упорядоченную работу и не дать людям скучать?
- В новом проекте сделай одну и только одну вещь по-другому. За счёт новизны появится энергия и в среднем она компенсирует низкую эффективность на начальном этапе.
- Проведи хакатон - на выходных - обстановка будет немного иная, а дух соревнований придаст дополнительную энергию.
- Проведи мозговой штурм: в этом формате все идеи записываются без оценки и это помогает по-новому взглянуть на проблемы. Кроме того это вовлекает больше людей.
- Неожиданный ланч, если денег мало.
- Поездка на конференцию (важна смена места), если денег достаточно.

*** Глава 25. Работа в офисе с 9 до 18 или есть варианты поинтереснее?
- Интрапренер - руководящий сотрудник фирмы, который решает неформальную задачу: помогает фирме находить и решать проблемы, делая ее более эффективной.
- Нужно заметить таких людей и работать с ними, стараясь не ограничивать их свободу в работе.

*** Глава 26. Как начать изменения?
- Не делай все сам: можно рассказать о проблеме другим и спросить, что они об этом думают.
- Действуй сообща с другими.


** VI. Что изменилось в индустрии за 20 лет?
*** Глава 27. Как сломать кристаллизовавшуюся команду?
- Наличие плаката с мотивирующим посланием говорит о том, что в этой фирме как раз проблема с этим. Профессионалы мотивированы изнутри, им не нужна такая внешняя мотивация.
- Ответь на вопрос: за счёт чего ты работаешь сверхурочно и на кого и как это влияет?
- Не каждый человек в команде сможет работать сверхурочно долгое (недели и месяцы) время.
- Люди могут работать сверхурочно, чтобы оградить себя от обвинений, что они не старались. Нужно работать с причиной нереальных сроков, а не перерабатывать.

*** Глава 28. Нужна ли конкуренция внутри команды? А между командами?
- Конкуренция внутри команды скорее вредна. Она будет мешать членам команды как обучать других, так и учиться у них.
- Конкуренция между командами скорее полезна. Она должна быть позитивна: мы обеспечиваем лучшее качество на этом рынке.
- Прямое выделение участников команд создаёт конкуренцию и мешает кристаллизации команды. См. Деминг «Выход из кризиса»
- Музыкальная группа как метафора лучше, чем спортивная команда. Нужно, чтобы связь устанавливалась между успехом и неуспехом команды, а не отдельных людей в команде.

*** Глава 29. Похоже ли движение за улучшение процессов на старые методологии для немотивированных людей?
- Предпочитай стандартные интерфейсы, а не стандартные процессы.
- Новые проекты повышают риск и требования к команде. Стандартные процессы рассчитаны на типовые ситуации, принимать решения придётся.

*** Глава 30. Сопротивляются ли люди переменам, даже позитивным?
- Да, сопротивляются (некоторые активно), особенно те, кто выигрывает от текущего положения вещей.
- При внедрении новой системы нужно подчеркивать (и это правда), что система принесла много пользы.
- Модель Сатир:
  - 1. Прежний статус кво.
  - 2. Привносится внешний элемент и возникает хаос. Падает производительность, кажется, что изменения делают только хуже. Из-за этого люди могут быть очень эмоциональны.
  - 3. Преобразующая идея: вносится структура (например, обучающие встречи), хотя беспорядок сохраняется.
  - 4. Практика и интеграция - люди начинают учиться и видят пользу, хоть и не могут действовать с хорошей производительностью.
  - 5. Новый статус кво - новый навык вошёл в обычную жизнь и стал работой.
- Для прохождения через хаос и обучения люди должны чувствовать себя в безопасности. Если возникнет паника изменения не пройдут. Неудача должна быть допустима, пусть и отчасти. Без этого не научиться.

*** Глава 31. Сколько стоят увольнение и найм сотрудника?
- Сначала новый сотрудник не сможет делать задачи уволившегося сотрудника. Даже наоборот, его онбординг будет отнимать время у других членов команды.
- Выход на производительность может занять от 3 и более месяцев.
- Если зарплату рассмотреть как актив, то станет понятно, что людей нужно удерживать.

*** Глава 32. Когда использовать обучение в фирме?
- Когда в фирме низкая текучка: одни люди будут учить других и фирма будет расти.
- Если у тебя в фирме высокая текучка, то нужно решать эту проблему первой, если ты хочешь делать более сложные проекты.
- Обычно обучение инициируют руководители среднего звена. Но можно начинать с самого низа, хоть это и сложнее (нет полномочий).

*** Глава 33. Какая самая серьезная ошибка руководителя?
- Впустую тратить время других людей.
- Стендап - это тоже церемония?
- Вырывать сотрудников из потока за счёт дробления  их времени разными задачами.

*** Глава 34. Что самое важное?
- Обьединить людей и дать им общину. Пример: построить здания фирмы вокруг дет сада и начальной школы.
