* 🦅 Проект «Феникс». Роман о том, как DevOps меняет бизнес к лучшему / Ким Джин, Спаффорд Джордж, Бер Кевин

** Начальная ситуация
- Отдел безопасности вносит изменения без учета того, как бы это помогло бизнесу.
- Отдел безопасности пытаются изолировать от обсуждения так как он воспринимается как помеха.
- В фирме есть узкое звено - инженер Брент, который фиксит сбои в то время как должен работать над критически важным опаздывающим проектом.


** Первые изменения
- Менеджер защитил узкое звено от незапланированной работы. Без этого все остальные шаги не принесут ничего.
  - Менеджер наблюдал за Брентом и сделал 2 изменения. Поставил перед ним буфер: человека, который отвечал за все входящие звонки, чтобы не отвлекать его от более приоритетной работы. А если Брент отвлекался, то команда училась тому, что он делал, чтобы в следующий раз она могла сама решить эту проблему.
- Менеджер классифицировал 4 типа работы:
  - Бизнес-проекты
  - Внутренние проекты
  - Изменения
  - Незапланированная работа (тушение пожаров, оно автоматом отвлекает ресурсы, отведенные на запланированную работу)
- Менеджеры договорились на неделю не брать в работу ничего кроме приоритетного проекта. Это разгрузило узкое звено и позволило продвинуться вперед по проекту.


** Дальнейшие изменения
  - В работу берутся только задачи, которые сейчас или позже увеличат пропускную способность ограничения. Это самый главный критерий. Применяется уже не только к Бренту, но и к другим ограничениям (если для них другой ресурс является ограниченным).
  - Канбан доска для визуализации работы:
    - Время ожидания ресурса пропорционально проценту времени когда ресурс занят к проценту времени когда ресурс свободен: 50/50 против 90/10. Важно сделать время ожидания видимым.
  - 20% времени отводится на улучшение инфраструктуры.
  - Определяется 5 приоритетных бизнес проектов, остальные в работу не берутся.


** 3 пути
  - 1. Оптимизировать работу всей системы, а не отдельных частей (фирма/подразделение или команда/член команды).
    - Нужно точно знать где находится узкое звено.
  - 2. Использовать обратную связь для точечных (в узких местах) улучшений системы.
    - Проблему аудита оказалось можно было не решать в лоб.
  - 3. Культура экспериментов и постоянного обучения-совершенствования.
    - Тренировка по 5 минут каждый день лучше, чем 3 часа раз в неделю.
