* ⚙️ Теория ограничений Голдратта. Системный подход к непрерывному совершенствованию / Детмер Уильям

** Глава 1. С чего начинается менеджмент?
- С определения цели. Что мы хотим получить?
- Дальше нужно понять где мы сейчас.
- Затем понять насколько большие преобразования нужно сделать.
- Без этих трех шагов нельзя браться за сами преобразования.

- Для достижения цели нужно выполнить одно или несколько необходимых условий.
- Систему производства можно описать как цепь: последовательность технологических этапов. Один из этапов является ограничением системы: нет смысла улучшать в другом месте, надо укреплять самое слабое звено.


** Глава 2. Какими качествами должны обладать логические построения?
  - 1. Ясность: все участники должны понимать и одинаково трактовать смысл терминов. Задача не согласиться с тем, что явление или факт имеет место, а именно гоаорить об одном и том же без подмены.
  - 2. Наличие утверждения: является законченной мыслью, не содержит скрытой логической связи внутри и не отметается сразу как бессмысленное.
  - 3. Законченность: есть субьект действия и само действие, отсутствуют неличные местоимения (этот, это, тот).
  - 4. Структура: утверждение является простым и содержит только один факт без скрытых связей "если ..., то ...". Чем проще формулировка, тем лучше.
  - 5. Содержание: утверждение реально существует ("небо падает" опровергается здравым смыслом).
  - 6. Наличие причинно-следственной связи. Иногда между утверждениями нет связи "если ..., то ..." или она связь направлена в другую сторону.
  - 7. Достаточность: достаточно ли приведенной причины? Это вопрос к стрелке, а не к утверждениям.
  - 8. Эллипс: выбирай максимум 3-4 причины, которые совместно приводят к следствию.
  - 9. Может ли быть альтернативная причина?

** Глава 3. Как найти ключевую проблему?
  - Построить причинно-следственные связи между нежелательными и желательными явлениями.
  - Не всегда связь является причинно-следственной. Например, покупка акций может приводить к прибыли, а может быть просто корреляцией и вскоре привести к убыткам. Может существовать некое условие помимо покупки акций, которое даст прибыль.

  - Алгоритм построения ДТР:
  - 1. Определи какие явления находятся в зоне контроля, какие в сфере влияния, а на какие мы не можем повлиять.
  - 2. Сформулируй в одном предложении суть проблемы. Если сформулировать не получается, значит проблемы нет. Пример: средняя задача занимает 3 дня от взятия в работу до выпуска.
  - 3. Задай вопрос к проблеме и сформулируй нежелательные явления. Пример, почему средняя задача делается 3 дня? Почему это плохо? Что с задачей происходит в эти 3 дня? Ответы на эти вопросы должны дать перечень нежелательных явлений: задачи приходится переделывать, задачи тестируются и ревьювятся 70% времени, разработчик переключается между задачами и т.п. НЯ должны быть понятны сами по себе, иначе это не НЯ. Используй критерии проверки логических построений из главы 2.
  - 4. Перенести список НЯ на диаграмму сначала БЕЗ связей. Нужно просто их расположить в горизонтальный список без системы.
  - 5. Выбери 2 НЯ, которые ты думаешь как-то связаны. Проверь являются ли они причиной и следствием. Причина должна находиться под следствием.
  - 6. Повтори эту процедуру для остальных НЯ, беря их по 2. По ходу проверяй не пропущены ли промежуточные элементы. Если да, то добавь их. Если несколько элементов вместе необходимы для следствия, то добавь эллипс.
  - 7. В идеале 50-70% будут иметь корневую причину. То есть будет V-образная структура, из которой выйдут несколько НЯ.
  - 8. Эта причина, должна находится в зоне влияния или в зоне контроля. Если нет, то ишем другую.
  - Если в основе ключевой проблемы лежит конфликт, то используем диаграмму разрешения конфликиов, иначе дерево будущей реальности.
  -
  -
